SIS/Models/ClassStudent.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ClassStudent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClassStudent()
        {
            this.Attendances = new HashSet<Attendance>();
            this.CourseWorks = new HashSet<CourseWork>();
            this.ReportCards = new HashSet<ReportCard>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Course_ModuleId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> Day { get; set; }
        public Nullable<int> Exam_Day { get; set; }
        public Nullable<int> Trial_Day { get; set; }
        public Nullable<int> Project_Day { get; set; }
        public Nullable<bool> Status { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual Course_Module Course_Module { get; set; }
        public virtual Student Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseWork> CourseWorks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportCard> ReportCards { get; set; }
    }
}

SIS/Controllers/ClassStudentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SIS.Models;

namespace SIS.Controllers
{
    [Authorize(Roles = "Admin, Sub Admin")]
    public class ClassStudentsController : Controller
    {
        private SISEntities db = new SISEntities();

        // GET: ClassStudents
        public ActionResult Index(int? id,int? Search)
        {
            if (Search == null)
            {
                var classStudents = db.ClassStudents.Include(c => c.Course_Module).Include(c => c.Student).OrderBy(x => x.Course_ModuleId).Where(x => x.Status == true);
                return View(classStudents.ToList());
            }
            else
            {
                var convert = Convert.ToBoolean(Search);
                var resultName = db.ClassStudents.Include(c => c.Course_Module).Include(c => c.Student).OrderBy(x => x.Course_ModuleId).Where(x => x.Status == convert);
                return View(resultName.ToList());
            }

            
        }

        public ActionResult CreateNewDetail(int? id, DateTime id2)
        {
            var getdata = db.ClassStudents.Where(x => x.Course_ModuleId == id && x.CreateDate == id2);
            return View(getdata);

        }

        public ActionResult deletecreate(int? id)
        {
            var select = db.ClassStudents.Where(x => x.Course_ModuleId == id);

            foreach (var item in select.ToList())
            {
                
                var finding = db.ClassStudents.Single(x => x.Course_ModuleId == item.Course_ModuleId && x.StudentId == item.StudentId);
                finding.Status = false;
                db.Entry(finding).State = EntityState.Modified;
            }
            //ClassStudent classStudent = db.ClassStudents.Find(id);
            //db.ClassStudents.Remove(classStudent);
            db.SaveChanges();
            return RedirectToAction("Index");
        }





        // GET: ClassStudents/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ClassStudent classStudent = db.ClassStudents.Find(id);
            if (classStudent == null)
            {
                return HttpNotFound();
            }
            return View(classStudent);
        }

        // GET: ClassStudents/Create
        public ActionResult Create()
        {
            var moduleName = from l in db.Course_Module
                             join c in db.Modules on l.ModuleId equals c.ModuleCode
                             select new { l.Id, Name = l.CourseId + "  (" + c.ModuleCode + ")" };

            var studentName = from s in db.Students
                              select new { s.Id, Name = s.Name + "(" + s.StudentId + ")" };

            ViewBag.Course_ModuleId = new SelectList(moduleName, "ID", "Name");
            ViewBag.StudentId = new MultiSelectList(studentName, "ID", "Name");



            return View();
        }

        // POST: ClassStudents/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ClassStudent classStudent)
        {
            if (ModelState.IsValid)
            {

                if(classStudent.StudentList != null && classStudent.StudentList.Count() > 0)
                {
                    if (classStudent.Status == null)
                    {
                        classStudent.Status = Convert.ToBoolean(1);
                    }
                    List<ClassStudent> cs = new List<ClassStudent>();


                    DateTime todaydate = DateTime.Now.Date;

                    var checking = db.ClassStudents.Any(x => x.Course_ModuleId == classStudent.Course_ModuleId && x.CreateDate == todaydate);
                    if (checking)
                    {
                        var moduleName = from l in db.Course_Module
                                         join c in db.Modules on l.ModuleId equals c.ModuleCode
                                         select new { l.Id, Name = l.CourseId + "  (" + c.ModuleCode + ")" };

                        ModelState.AddModelError("", "You have already create THIS class today !");
                        ViewBag.Course_ModuleId = new SelectList(moduleName, "ID", "Name");
                        ViewBag.StudentId = new MultiSelectList(db.Students, "ID", "Name");
                        return View(classStudent);
                    }
                    else
                    {


                        foreach (var i in classStudent.StudentList)
                        {

                            cs.Add(new ClassStudent { StudentId = i, Course_ModuleId = classStudent.Course_ModuleId, Day = classStudent.Day, Exam_Day = 1, Trial_Day = 1, Project_Day = 1, CreateDate = DateTime.Now, Status = true });
                        }
                        db.ClassStudents.AddRange(cs);
                    }
                }

                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Course_ModuleId = new SelectList(db.Course_Module, "Id", "CourseId", classStudent.Course_ModuleId);
            ViewBag.StudentId = new SelectList(db.Course_Module, "Id", "StudentId", classStudent.StudentId);
            return View(classStudent);
        }

        // GET: ClassStudents/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ClassStudent classStudent = db.ClassStudents.Find(id);
            if (classStudent == null)
            {
                return HttpNotFound();
            }
            ViewBag.Course_ModuleId = new SelectList(db.Course_Module, "Id", "CourseId", classStudent.Course_ModuleId);
            ViewBag.StudentId = new SelectList(db.Students, "ID", "Name", classStudent.StudentId);
            return View(classStudent);
        }

        // POST: ClassStudents/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ClassStudentId,Course_ModuleId,StudentId")] ClassStudent classStudent)
        {
            if (ModelState.IsValid)
            {
                db.Entry(classStudent).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Course_ModuleId = new SelectList(db.Course_Module, "Id", "CourseId", classStudent.Course_ModuleId);
            ViewBag.StudentId = new SelectList(db.Students, "ID", "Name", classStudent.StudentId);
            return View(classStudent);
        }

        // GET: ClassStudents/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ClassStudent classStudent = db.ClassStudents.Find(id);
            if (classStudent == null)
            {
                return HttpNotFound();
            }
            return View(classStudent);
        }

        // POST: ClassStudents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ClassStudent classStudent = db.ClassStudents.Find(id);
            db.ClassStudents.Remove(classStudent);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
     

        public ActionResult Pass(int id)
        {
            return RedirectToRoute(new { Controller = "ModuleStandards", Action = "Add", id = id });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SIS/Views/ClassStudents/CIndex.cshtml
@model IEnumerable<SIS.Models.ClassStudent>

@{
    ViewBag.Title = "CIndex";
}

<h2>CIndex</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Day)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Course_Module.CourseId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Student.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Day)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Course_Module.CourseId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Student.Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

SIS/Views/ClassStudents/ClassAvailable.cshtml
@model IEnumerable<SIS.Models.Course_Module>

@{
    ViewBag.Title = "ClassAvailable";
}

<h2>Class Available</h2>

@*<p>
        @Html.ActionLink("Create New", "Create")
    </p>*@

<br>


@using (Html.BeginForm("ClassAvailable", "ClassStudents", FormMethod.Get))
{
    @Html.DropDownList("Search", new List<SelectListItem>

                    {
                        new SelectListItem{ Text="-- Select Class Status --", Value = ""},
                        new SelectListItem{ Text="Active", Value = "1" },
                        new SelectListItem{ Text="Deactive", Value = "0" },
                    }, htmlAttributes: new { @class = "" })

    <input type="submit" class="btn btn-default" value="Search" />
}

<br>





<table class="table">

    @{
        int count = Model.Count();
    }

    @if (count == 0)
    {

        <tr>
            <th>
                <br>
                <bold>
                    Does Not Have Class Available !<br>
                </bold>
            <th>
        </tr>
    }
    else
    {
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Course.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Module.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Trainer.Name)
            </th>
            <th></th>
        </tr>

        foreach (var item in Model)
        {
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Course.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Module.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Trainer.Name)
                </td>
                <td>
                    @Html.ActionLink("Set Standard", "Pass", new { item.Id })
                </td>
            </tr>
        }

    }

</table>

SIS/Views/ClassStudents/Create.cshtml
@model SIS.Models.ClassStudent

@{
    ViewBag.Title = "Create a New Class";
}
<br />
@section Menu {
    @Scripts.Render("~/Scripts/Forms/Advanced/menu")
}

@Styles.Render("~/Content/plugins/select2/css")
@Styles.Render("~/Content/plugins/icheck/css")
@Styles.Render("~/Content/dist/css")
@Styles.Render("~/Content/dist/css/skins")

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.Label("Course_ModuleId", "Module", htmlAttributes: new { @class = "control-label col-xs-2" })
            <div class="col-xs-4">
                @Html.DropDownList("Course_ModuleId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessage("Course_ModuleId", "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.StudentList, htmlAttributes: new { @class = "control-label col-xs-2" })
            <div class="col-xs-4">
                @Html.ListBoxFor(model => model.StudentList, ViewBag.StudentId as MultiSelectList, new { @multiple = "multiple", @class = "from-control select2", @style = "width:100%" })
                @Html.ValidationMessage("StudentList", "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Day, htmlAttributes: new { @class = "control-label col-xs-2" })
            <div class="col-xs-4">
                @Html.EditorFor(model => model.Day, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Day, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <div class="col-xs-offset-2 col-xs-4">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
@Scripts.Render("~/Content/plugins/select2/js")
    @Scripts.Render("~/Content/plugins/jquery-validate/js")
@Scripts.Render("~/Content/plugins/bootstrap-multiselect")
@Scripts.Render("~/bundles/jquerymask")
@Scripts.Render("~/Content/plugins/input-mask/js")
@Scripts.Render("~/Content/plugins/icheck/js")
@Scripts.Render("~/Scripts/Forms/Advanced")
<script>
    $(document).ready(function () {

        $('.multiselectddl').multiselect();
    });
</script>
<script src="~/Scripts/jquery.maskedinput.js" type="text/javascript"></script>
<script>
        $(document).ready(function() {
            $("#Lab_ExpireDate").inputmask("date");
        });
</script>
}

SIS/Views/ClassStudents/CreateNewDetail.cshtml
@model IEnumerable<SIS.Models.ClassStudent>

@{
    ViewBag.Title = "Student in this class";
}

<br/>

@*<p>
    @Html.ActionLink("Add Student to this class", "Create")
</p>*@
<table class="table">
    <tr>
        @*<th>
            @Html.DisplayNameFor(model => model.Day)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Exam_Day)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Trial_Day)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Project_Day)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Lab_ExpireDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Course_Module.CourseId)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.Student.StudentId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Student.Name)
        </th>

        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        @*<td>
            @Html.DisplayFor(modelItem => item.Day)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Exam_Day)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Trial_Day)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Project_Day)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Lab_ExpireDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Course_Module.CourseId)
        </td>*@
        <td>
            @Html.DisplayFor(modelItem => item.Student.StudentId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Student.Name)
        </td>


    </tr>
}

</table>

SIS/Views/ClassStudents/Delete.cshtml
@model SIS.Models.ClassStudent

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ClassStudent</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Course_Module.CourseId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course_Module.CourseId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Student.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Student.Name)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SIS/Views/ClassStudents/Details.cshtml
@model SIS.Models.ClassStudent

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ClassStudent</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Course_Module.CourseId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Course_Module.CourseId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Student.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Student.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Day)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Day)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SIS/Views/ClassStudents/Edit.cshtml
@model SIS.Models.ClassStudent

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>ClassStudent</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Course_ModuleId, "Course_ModuleId", htmlAttributes: new { @class = "control-label col-xs-2" })
            <div class="col-xs-4">
                @Html.DropDownList("Course_ModuleId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Course_ModuleId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StudentId, "StudentId", htmlAttributes: new { @class = "control-label col-xs-2" })
            <div class="col-xs-4">
                @Html.DropDownList("StudentId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.StudentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/Content/plugins/jquery-validate/js")
}

SIS/Views/ClassStudents/Index.cshtml
@model IEnumerable<SIS.Models.ClassStudent>

@{
    ViewBag.Title = "Student Are In Class";
}
<br />

<p>
    @Html.ActionLink("Create New Class", "Create")
</p>

<br>

@using (Html.BeginForm("Index", "ClassStudents", FormMethod.Get))
{
    @Html.DropDownList("Search", new List<SelectListItem>

                    {
                        new SelectListItem{ Text="-- Select Class Status --", Value = ""},
                        new SelectListItem{ Text="Active", Value = "1" },
                        new SelectListItem{ Text="Deactive", Value = "0" },
                    }, htmlAttributes: new { @class = "" })



    <input type="submit" class="btn btn-default" value="Search" />
}

<br />

<table class="table">
@{
    int count = Model.Count();
}

@if (count == 0)
{

    <tr>
        <th>
            <br>
            <bold>
                Does Not Have Class Available !<br>
            </bold>
        <th>
    </tr>
}
else
{
    <tr>
        <th>
            Course Name
        </th>
        <th>
            Module Name
        </th>
  
        <th>
            Create Date
        </th>
        <th>
            Status
        </th>


        <th></th>
    </tr>



    int? same = 0;
    string date = "";


    foreach (var item in Model)
    {

        if (item.Course_ModuleId != same || item.CreateDate.Value.ToShortDateString() != date)
        {
            same = item.Course_ModuleId;
            date = item.CreateDate.Value.ToShortDateString();

            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Course_Module.CourseId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Course_Module.Module.ModuleCode)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreateDate)
                </td>
                @if (item.Status == true)
                {
                    <td>
                        Active
                    </td>
                }
                else if (item.Status == false)
                {
                    <td>
                        Deactive
                    </td>                
                }
                <td>
                    @Html.ActionLink("Student in this class", "CreateNewDetail", new { id = item.Course_ModuleId, id2 = item.CreateDate }) |
                    @if (item.Status == false)
                    {


                    }
                    else
                    {
                     @Html.ActionLink("Delete", "deletecreate", new { id = item.Course_ModuleId })
                    }
                </td>
            </tr>
        }
        else
        {
            continue;
        }


    }
}



</table>