SIS/Models/Invoice.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int Id { get; set; }
        public Nullable<int> StudentId { get; set; }
        public string Ref { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Description { get; set; }
        public string Description2 { get; set; }
        public string Description3 { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Amount2 { get; set; }
        public Nullable<decimal> Amount3 { get; set; }
        public Nullable<decimal> GST { get; set; }
        public Nullable<decimal> GST2 { get; set; }
        public Nullable<decimal> GST3 { get; set; }
        public Nullable<decimal> GSTAmt { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> FinalTotal { get; set; }
        public string Color { get; set; }
    
        public virtual Student Student { get; set; }
    }
}

SIS/Controllers/InvoiceController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SIS.Models;

namespace SIS.Controllers
{
    [Authorize(Roles = "Admin, Sub Admin")]
    public class InvoiceController : Controller
    {
        private SISEntities db = new SISEntities();

        // GET: Invoice
        //public ActionResult Index()
        //{
        //    var invoices = db.Invoices.Include(i => i.Student);
        //    return View(invoices.ToList());
        //}

        public ActionResult Index(string SearchString)
        {
            if (!String.IsNullOrEmpty(SearchString))
            {
                var temp = db.Invoices.OrderBy(i => i.Student.Name).Where(j => j.Student.Name.ToLower().Contains(SearchString.ToLower()));
                return View(temp);
            }
            var invoice = db.Invoices.Include(p => p.Student).Include(p => p.Student);
            return View(db.Invoices);
        }

        // GET: Invoice/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invoice invoice = db.Invoices.Find(id);
            if (invoice == null)
            {
                return HttpNotFound();
            }
            return View(invoice);
        }

        // GET: Invoice/Create
        public ActionResult Create()
        {
            ViewBag.StudentId = new SelectList(db.Students, "Id", "Name");
            return View();
        }

        // POST: Invoice/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,StudentId,Description,Description2,Description3,GST,GST2,GST3,Amount,Amount2,Amount3,GSTAmt,Ref,Total,FinalTotal,Date,Color")] Invoice invoice)
        {
            if (ModelState.IsValid)
            {
                if (invoice.GST == null)
                {
                    invoice.GST = 0;
                }

                if(invoice.GST2 == null)
                {
                    invoice.GST2 = 0;
                }

                if(invoice.GST3 == null)
                {
                    invoice.GST3 = 0;
                }

                if (invoice.Amount3 != null)
                {          
                    invoice.FinalTotal = invoice.Amount + invoice.Amount2 + invoice.Amount3;
                    invoice.GSTAmt = invoice.GST + invoice.GST2 + invoice.GST3;
                    invoice.Total = invoice.FinalTotal - invoice.GSTAmt;
                }
                else if (invoice.Amount2 != null)
                {            
                    invoice.FinalTotal = invoice.Amount + invoice.Amount2;
                    invoice.GSTAmt = invoice.GST + invoice.GST2;
                    invoice.Total = invoice.FinalTotal - invoice.GSTAmt;
                }
                else if (invoice.Amount != null)
                {
                    invoice.FinalTotal = invoice.Amount;
                    invoice.GSTAmt = invoice.GST;
                    invoice.Total = invoice.FinalTotal - invoice.GSTAmt;
                }

                db.Invoices.Add(invoice);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.StudentId = new SelectList(db.Students, "Id", "Name", invoice.StudentId);
            return View(invoice);
        }

        

        public ActionResult Invoice(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invoice invoice = db.Invoices.Find(id);
            if (invoice == null)
            {
                return HttpNotFound();
            }

            return View(invoice);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Invoice([Bind(Include = "Id,StudentId,Description,Description2,Description3,GST,GST2,GST3,Amount,Amount2,Amount3,GSTAmt,Ref,Total,FinalTotal,Date,Color")] Invoice invoice)
        {
            if (ModelState.IsValid)
            {
                db.Entry(invoice).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }                                                                          
            return View(invoice);
        }  



        // GET: Invoice/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invoice invoice = db.Invoices.Find(id);
            if (invoice == null)
            {
                return HttpNotFound();
            }
            ViewBag.StudentId = new SelectList(db.Students, "Id", "Name", invoice.StudentId);
            return View(invoice);
        }

        // POST: Invoice/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,StudentId,Description,Description2,Description3,GST,GST2,GST3,Amount,Amount2,Amount3,GSTAmt,Ref,Total,FinalTotal,Date,Color")] Invoice invoice)
        {
            if (ModelState.IsValid)
            {
                if (invoice.GST == null)
                {
                    invoice.GST = 0;
                }

                if (invoice.GST2 == null)
                {
                    invoice.GST2 = 0;
                }

                if (invoice.GST3 == null)
                {
                    invoice.GST3 = 0;
                }

                if (invoice.Amount3 != null)
                {
                    invoice.FinalTotal = invoice.Amount + invoice.Amount2 + invoice.Amount3;
                    invoice.GSTAmt = invoice.GST + invoice.GST2 + invoice.GST3;
                    invoice.Total = invoice.FinalTotal - invoice.GSTAmt;
                }
                else if (invoice.Amount2 != null)
                {
                    invoice.FinalTotal = invoice.Amount + invoice.Amount2;
                    invoice.GSTAmt = invoice.GST + invoice.GST2;
                    invoice.Total = invoice.FinalTotal - invoice.GSTAmt;
                }
                else if (invoice.Amount != null)
                {
                    invoice.FinalTotal = invoice.Amount;
                    invoice.GSTAmt = invoice.GST;
                    invoice.Total = invoice.FinalTotal - invoice.GSTAmt;
                }
                db.Entry(invoice).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.StudentId = new SelectList(db.Students, "Id", "Name", invoice.StudentId);
            return View(invoice);
        }

        // GET: Invoice/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Invoice invoice = db.Invoices.Find(id);
            if (invoice == null)
            {
                return HttpNotFound();
            }
            return View(invoice);
        }

        // POST: Invoice/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Invoice invoice = db.Invoices.Find(id);
            db.Invoices.Remove(invoice);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SIS/Views/Invoice/Create.cshtml
@model SIS.Models.Invoice

@{
    ViewBag.Title = "Create";
}

@section Menu {
    @Scripts.Render("~/Scripts/Forms/Advanced/menu")
}

@Styles.Render("~/Content/plugins/select2/css")
@Styles.Render("~/Content/dist/css")
@Styles.Render("~/Content/dist/css/skins")

<br />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()       
    
    <div class="form-horizontal">
        <h4>Invoice</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<div class="form-group">
            @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-xs-2" })
            <div class="col-xs-10">
                @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.StudentId, "StudentName", htmlAttributes: new { @class = "control-label col-xs-2 " })
            <div class="col-xs-4">
                @Html.DropDownList("StudentId", null, htmlAttributes: new { @class = "form-control select2" })
                @Html.ValidationMessageFor(model => model.StudentId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Ref,"Your Ref.", htmlAttributes : new { @class="control-label col-xs-2"})
            <div class="col-xs-4">
                @Html.DropDownList("Ref", new List<SelectListItem>
           {
               new SelectListItem {Text="Cash" , Value ="Cash" },
               new SelectListItem {Text ="Cheque", Value="Cheque" },
           }, htmlAttributes: new { @class="form-control"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-xs-2" })
            <div class="col-xs-4">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-xs-2" })
            <div class="col-xs-4">
                <input type="checkbox" onclick="click1()" id="checkbx1" /> include 6%(GST)
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control", id="txt1" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Description2, htmlAttributes: new { @class = "control-label col-xs-2" })
            <div class="col-xs-4">
                @Html.EditorFor(model => model.Description2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description2, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Amount2, htmlAttributes: new { @class = "control-label col-xs-2" })
            <div class="col-xs-4">
                <input type="checkbox" onclick="click2()" id="checkbx2" /> include 6%(GST)
                @Html.EditorFor(model => model.Amount2, new { htmlAttributes = new { @class = "form-control", id = "txt2" } })
                @Html.ValidationMessageFor(model => model.Amount2, "", new { @class = "text-danger" })
            </div>
        </div>

   

        <div class="form-group">
            @Html.LabelFor(model => model.Description3, htmlAttributes: new { @class = "control-label col-xs-2" })
            <div class="col-xs-4">
                @Html.EditorFor(model => model.Description3, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description3, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Amount3, htmlAttributes: new { @class = "control-label col-xs-2" })
            <div class="col-xs-4">
                <input type="checkbox" onclick="click3()" id="checkbx3" /> include 6%(GST)
                @Html.EditorFor(model => model.Amount3, new { htmlAttributes = new { @class = "form-control" , id = "txt3" } })
                @Html.ValidationMessageFor(model => model.Amount3, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.HiddenFor(model => model.GST, new { @id = "Gst1" })
        @Html.HiddenFor(model => model.GST2, new { @id = "Gst2" })
        @Html.HiddenFor(model => model.GST3, new { @id = "Gst3" })



        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-xs-2" })
            <div class="col-xs-4">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Color, htmlAttributes: new { @class = "control-label col-xs-2" })
            <div class="col-xs-1" style="width: 10%">
                @Html.EditorFor(model => model.Color, new { htmlAttributes = new { @class = "form-control", @type = "color" } })
                @Html.ValidationMessageFor(model => model.Color, "", new { @class = "text-danger" })
            </div>
        </div>


        @*<div class="form-group">
            @Html.LabelFor(model => model.GSTAmt, htmlAttributes: new { @class = "control-label col-xs-2" })
            <div class="col-xs-4">
                @Html.EditorFor(model => model.GSTAmt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GSTAmt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Total, htmlAttributes: new { @class = "control-label col-xs-2" })
            <div class="col-xs-4">
                @Html.EditorFor(model => model.Total, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Total, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FinalTotal, htmlAttributes: new { @class = "control-label col-xs-2" })
            <div class="col-xs-4">
                @Html.EditorFor(model => model.FinalTotal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FinalTotal, "", new { @class = "text-danger" })
            </div>
        </div>*@

        
            @*<div class="input-group date" data-provide="datepicker">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-xs-2" })  
                <div class="col-xs-4">
                    @Html.TextBoxFor(model => model.Date, htmlAttributes: new { @class = "form-control", id ="datepicker" })
                        <div class="input-group-addon">
                             <span class="glyphicon glyphicon-th"></span>
                        </div>
               </div>
        </div>*@


        <div class="form-group">
            <div class="col-xs-offset-2 col-xs-4">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<script type="text/javascript">
    function click1()
    {     
        var checkBoxMI = $('#checkbx1');                   
        var x = document.getElementById("txt1").value;
        if (checkBoxMI.is(':checked'))
        {
            document.getElementById("Gst1").value = x - ((x * 100) / 106)
        }
    }

    function click2()
    {
        var checkBoxMI = $('#checkbx2');
        var x = document.getElementById("txt2").value;
        if (checkBoxMI.is(':checked'))
        {
            document.getElementById("Gst2").value = x - ((x * 100) / 106)
        }
    }

    function click3() {
        var checkBoxMI = $('#checkbx3');
        var x = document.getElementById("txt3").value;
        if (checkBoxMI.is(':checked'))
        {
            document.getElementById("Gst3").value = x - ((x * 100) / 106)
        }
    }


</script>


<div>
    @Html.ActionLink("Back", "Index", null, new { @class = "btn btn-primary" })
</div>

@section scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Content/plugins/select2/js")
    @Scripts.Render("~/Scripts/Forms/Advanced")
}

@*@section Scripts {
    <script>
        $('#sandbox-container .input-group.date').datepicker({
            todayBtn: "linked",
            autoclose: true
        });

    </script>
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Content/plugins/datepicker/js")
    @Scripts.Render("~/Content/plugins/datepicker/css")
}*@

SIS/Views/Invoice/Delete.cshtml
@model SIS.Models.Invoice


<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Invoice</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GSTAmt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GSTAmt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Total)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Total)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FinalTotal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FinalTotal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Student.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Student.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SIS/Views/Invoice/Invoice.cshtml
@model SIS.Models.Invoice


@section Menu {
    @Scripts.Render("~/Scripts/Examples/Invoice/menu")
}
   <script>

   </script>

<div class="invoice" style="margin-left: 0 !important; margin-right: 0 !important;">
    <div class="row">
        <div class="col-xs-12">
            <img src="/Content/image/Companylogo.jpg" alt="CompanyLogo" style="width: 390px; height: 100px" />
            <address class="pull-right">
                <strong>SBIT TRAINING SDN. BHD.</strong> (894857-H)<br>
                18A, Jalan 20/16A, Taman Paramount,<br>
                46300 Petaling Jaya, Selangor.<br>
                info@sbit.edu.my * www.sbit.edu.my<br>
                Tel : 603-78774668<br>
                <b>(GST No: 001194561536)</b>
            </address>
        </div>
        <div class="text-center">
            <h2>TAX INVOICE</h2>
            <hr />
        </div>
    </div>
    <div class="row invoice-info">
        <div class="col-sm-4 invoice-col">
            <address>
                <strong>
                    @Html.DisplayFor(model => model.Student.Name, new { htmlAttribute = new { @class = "form-control" } }) <br />
                @foreach (var x in Model.Student.Addresses)
                {
                    @Html.DisplayFor(model => x.StreetLine1)<br />
                    @Html.DisplayFor(model => x.StreetLine2)<br />
                    @Html.DisplayFor(model => x.PostCode)<br />
                    @Html.DisplayFor(model => x.State)<br />
                    @Html.DisplayFor(model => x.Country)
                }
            </strong>
            <br>
            <br />
            <br />
            TEL:&emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; &emsp; FAX:
        </address>
    </div>
    @*This for space*@
    <div class="col-sm-4 invoice-col">
        <address>
            <strong> </strong><br>
            <br>
            <br>
            <br>
        </address>
    </div>
    <div class="col-sm-4 invoice-col">
        <b>Receipt No &nbsp; &nbsp; &nbsp; &nbsp;: CS- @Html.DisplayFor(model => model.Id, new { htmlAttribute = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })</b><br>
        Your Ref. &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;: @Html.DisplayFor(model => model.Ref, new { htmlAttribute = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })<br>
        Ext. No &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; :<br>
        Terms &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; : C.O.D.<br>
        Date &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;: @Html.DisplayFor(model => model.Date, new { htmlAttribute = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })<br />
        @*Page &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;: 1 of 1<br />*@
        @*A/C No &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;: 300-00001*@
    </div>
</div>
<div class="row">
    <div class="col-xs-12 table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    @*<th>No</th>*@
                    <th>Description</th>
                    <th></th>
                    <th></th>
                    @*<th>Qty</th>*@
                    @*<th>Price (RM)</th>*@
                    <th>Amount (RM)</th>
                    @*<th>TAX</th>*@
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        @Html.DisplayFor(model => model.Description, new { htmlAttribute = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </td>

                  <td></td>
                  <td></td> 
                @*<td>@Html.TextBox("simple", null, new { @class = "col-md-3" }) </td>*@

                @*<td>@Html.DisplayFor(model => model.Amount, new { htmlAttribute = new { @class = "col-md-3" } })
                        @Html.ValidationMessageFor(model => model.CourseId, "", new { @class = "text-danger" })
                    </td>*@

                <td>
                    @Html.DisplayFor(model => model.Amount, new { htmlAttribute = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </td>
                    
            @*<td>
                SR
            </td>*@
        </tr>

                <tr>
                    <td>
                        @Html.DisplayFor(model => model.Description2, new { htmlAttribute = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Description2, "", new { @class = "text-danger" })
                    </td>
                    <td></td>
                    <td></td> 

                    @*<td>@Html.TextBox("simple", null, new { @class = "col-md-3" }) </td>*@

                    @*<td>@Html.DisplayFor(model => model.Amount, new { htmlAttribute = new { @class = "col-md-3" } })
                @Html.ValidationMessageFor(model => model.CourseId, "", new { @class = "text-danger" })
            </td>*@

                    <td>
                        @Html.DisplayFor(model => model.Amount2, new { htmlAttribute = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Amount2, "", new { @class = "text-danger" })
                    </td>

                    <td></td>
                </tr>

                <tr>
                    <td>
                        @Html.DisplayFor(model => model.Description3, new { htmlAttribute = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Description3, "", new { @class = "text-danger" })
                    </td>
                    <td></td>
                    <td></td>

                    @*<td>@Html.TextBox("simple", null, new { @class = "col-md-3" }) </td>*@

                    @*<td>@Html.DisplayFor(model => model.Amount, new { htmlAttribute = new { @class = "col-md-3" } })
                @Html.ValidationMessageFor(model => model.CourseId, "", new { @class = "text-danger" })
            </td>*@

                    <td>
                        @Html.DisplayFor(model => model.Amount3, new { htmlAttribute = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Amount3, "", new { @class = "text-danger" })
                    </td>

                   <td></td>
                </tr>
    </tbody>
</table>
<hr />
</div>
</div>
<div class="row">
    <div class="col-xs-6">
        @*<p class="lead">RINGGIT MALAYSIA : TWO THOUSAND ONLY</p>*@
        <p>
            Notes:<br />
            1. All cheques should be crossed and made payable to<br />
            <b>SBIT TRAINING SDN. BHD.</b><br />
            2. Goods sold are neither returnable nor refundable.<br />
        </p>
    </div>
    <div class="col-xs-6">
        <div class="table-responsive">
            <table class="table">
                <tr>
                    <th style="width: 35%">Total (RM)</th>
                    <td>@Html.DisplayFor(model => model.Total, new { htmlAttribute = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Total, "", new { @class = "text-danger" })</td>
                </tr>
                <tr>
                    <th>GST Amt</th>
                    <td>@Html.DisplayFor(model => model.GSTAmt, new { htmlAttribute = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.GSTAmt, "", new { @class = "text-danger" })</td>
                </tr>
                @*<tr>
                    <th>Rounding Total</th>
                    <td></td>
                </tr>*@
                <tr>
                    <th>Final Total</th>
                    <td>@Html.DisplayFor(model => model.FinalTotal, new { htmlAttribute = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FinalTotal, "", new { @class = "text-danger" })</td>
                </tr>
            </table>
        </div>
    </div>
</div>

    <script type="text/javascript">
        function print_page() {
            var ButtonControl = document.getElementById("btnprint");
            ButtonControl.style.visibility = "hidden";
            window.print();
            ButtonControl.style.visibility = "visible";
        }
    </script>

    <p>
        <input type="button" id="btnprint" value="Print" onclick="print_page()" />
    </p>

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>


@*<div class="row no-print">
    <div class="col-xs-12">
        <a href="@Url.Action("InvoicePrint", "Invoice")" target="_blank" class="btn btn-default pull-right"><i class="fa fa-print"></i> Print</a>
    </div>
</div>*@
             
<div class="clearfix"></div>
</div>